// <auto-generated />
using MegaCoreBackEnd.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MegaCoreBackEnd.Migrations
{
    [DbContext(typeof(EFDataContext))]
    [Migration("20221017091751_migrate1")]
    partial class migrate1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MegaCoreBackEnd.Models.Msstoragelocation", b =>
                {
                    b.Property<string>("location_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("location_name")
                        .HasColumnType("varchar(100)");

                    b.HasKey("location_id");

                    b.ToTable("ms_storage_location","dbo");
                });

            modelBuilder.Entity("MegaCoreBackEnd.Models.Trbpkb", b =>
                {
                    b.Property<string>("agreement_number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("location_id")
                        .HasColumnType("varchar(10)");

                    b.HasKey("agreement_number");

                    b.HasIndex("location_id");

                    b.ToTable("tr_bpkb","dbo");
                });

            modelBuilder.Entity("MegaCoreBackEnd.Models.Trbpkb", b =>
                {
                    b.HasOne("MegaCoreBackEnd.Models.Msstoragelocation", "Msstoragelocation")
                        .WithMany()
                        .HasForeignKey("location_id");
                });
#pragma warning restore 612, 618
        }
    }
}
